\name: Create and publish a Docker image

on:
  workflow_dispatch: # Enables manual trigger
  push:
    branches:
      - 'dev'
    paths:
      - 'Dockerfile'

jobs:
  docker:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: docker/github-builder/.github/workflows/build.yml@v1
    with:
      platforms: linux/amd64,linux/arm64
      output: image
      push: true
      meta-images: ghcr.io/${{ github.repository }}
      meta-tags: |
        type=raw,value=latest
        type=sha,format=short
      cache: true
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
