name: Create and publish a Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
    paths:
      - 'Dockerfile'

jobs:
  docker:
    permissions:
      id-token: write
    uses: docker/github-builder/.github/workflows/build.yml@v1
    with:
      platforms: linux/amd64,linux/arm64
      output: type=registry
      target-tags: |
        ghcr.io/${{ github.repository }}:latest
        ghcr.io/${{ github.repository }}:sha-${{ github.sha }}
      registry-username: ${{ github.actor }}
      registry-password: ${{ secrets.GITHUB_TOKEN }}
      cache-from: type=gha
      cache-to: type=gha,mode=max
